cmcs/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path,include
from user.views import dashboard,content,allocateChild,chat,reply,comment,passwordreset,viewTasks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path("", dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path('<int:id>/content/',content,name='content'),
    path('<int:id>/allocateChild/',allocateChild,name='allocateChild'),
    path('chat/',chat,name='chat'),
    path('<int:id>/chat/',reply,name='reply'),
    path('chat.../',comment,name='comment'),
    path('display/',viewTasks,name='tasks'),
    
    path('accounts/reset-password/', passwordreset, name='contact')
    
    

   
    
    
    
]

user/urls.py
from django.urls import path,include
from user.views import dashboard

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),

   
]

user/models.py
from django.db import models
import datetime
from django.conf import settings

# Create your models here.

class UserProfile(models.Model):
    user = models.ForeignKey( settings.AUTH_USER_MODEL, null = False, on_delete=models.CASCADE)
    child = models.ForeignKey(settings.AUTH_USER_MODEL, null = True, related_name = "+" ,on_delete=models.CASCADE)
    parent = models.ForeignKey(settings.AUTH_USER_MODEL, null = True,related_name = "+", on_delete=models.CASCADE)
    picture = models.TextField()
    team_name = models.CharField(max_length=100)
    is_password_reset = models.BooleanField(default = False)
    is_child_assigned = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return str(self.user)

class Comment(models.Model):
    
    user = models.ForeignKey( settings.AUTH_USER_MODEL, null = False, on_delete=models.CASCADE)
    comment=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    receiver=models.IntegerField(null=True)
    def __str__(self):
        return str(self.user)

class Reply(models.Model):
    user = models.ForeignKey( settings.AUTH_USER_MODEL, null = False, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE )
    comments=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.user)

user/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
  

user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from .models import UserProfile,Comment,Reply
from django.contrib.auth.models import User
from django.urls import reverse
from .forms import ContactForm
import random
import string
from django.core.mail import send_mail, BadHeaderError
import smtplib,ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import secrets
from django.contrib.auth import authenticate



@csrf_exempt
@login_required(login_url='/accounts/login/')
def dashboard(request):
    user_id = request.user.id
   
    profile = UserProfile.objects.get(id= user_id)
    
    if profile.is_password_reset == False :
        profile.is_password_reset = True
        profile.save()
        return redirect('password_change')

    if user_id:
        #logging in
        userprofile=UserProfile.objects.get(id=user_id)
        users = User.objects.all()
        profiles=UserProfile.objects.all()
        objects={'userprofile':userprofile,'u':users,'q':profiles,'UserProfile':UserProfile.objects.all()}
        return render(request, "user/dashboard.html",objects)
    else:
        #logging out
        return render(request, "user/dashboard.html")
    
    
    
@csrf_exempt
@login_required(login_url='/accounts/login/')
def content(request,id):
    user=UserProfile.objects.get(id=id)
    users = User.objects.all()
    profiles=UserProfile.objects.all()
    objects={'user':user,'u':users,'q':profiles,'UserProfile':UserProfile.objects.all()}
    return render(request,'user/content.html',objects)

@csrf_exempt
def allocateChild(request,id):
    child_id=random.randrange(95,176,)
    if is_freeChild(child_id,id):
        child=UserProfile.objects.get(id=child_id)
        child.parent_id=id
        child.save()
        parent=UserProfile.objects.get(id=id)
        parent.child_id=child_id
        parent.is_child_assigned=True
        parent.save()
    else:
        allocateChild(request,id)
    
    return HttpResponseRedirect(reverse('dashboard' ))

def is_freeChild(child_id,id):
    parent=UserProfile.objects.get(id=child_id)#for assuring that we are not assigning mom as child
    if child_id==id and child.child_id==id:
        return False
    child=UserProfile.objects.get(id=child_id)
    if child.parent_id:
        return False
    return True

@csrf_exempt
@login_required(login_url='/accounts/login/')
def chat(request):
    
    users = User.objects.all()
    return render(request,'user/commentbox.html',{'comments':Comment.objects.all(),'u':users})

@csrf_exempt
@login_required(login_url='/accounts/login/')
def reply(request,id):
    text=str(request.POST.get('reply'))
    
    if text !="" and  text.split()!=[]:
        reply=Reply(comment=Comment.objects.get(id=id),user=User.objects.get(id=(id+94)),comments=text)
        #reason for id+94-->user table id starts with 95

        reply.save()
        
    return HttpResponseRedirect(reverse('chat'))

@csrf_exempt
@login_required(login_url='/accounts/login/')
def comment(request):
    receiver=int(request.POST.get('menu'))
    text=request.POST.get('comment')
    if text !="" and  text.split()!=[]:
        comments=Comment(user=User.objects.get(id=int(request.user.id)),comment=request.POST.get('comment'),receiver=receiver)
        comments.save()
    return HttpResponseRedirect(reverse('chat'))

def passwordreset(request):
    if request.method == 'GET':
        form = ContactForm()
        
    else:

        form = ContactForm(request.POST)
        
        if form.is_valid():
            
            from_email = form.cleaned_data['from_email']
            #Object creation for User Table 
            a = User.objects.filter(email=from_email).first()
            
           
            if a != None:
                
                user_id = a.id
                #Object creation for UserProfile Table
                c = UserProfile.objects.get(user_id = user_id)
                c.is_password_reset = False
                c.save()
                N = 7 #size of the random string

                #random password generation
                rand = ''.join(random.choices(string.ascii_uppercase + string.digits, k = N))

                #Object creation for User Table
                d = User.objects.get(id = user_id)

                new_password = 'Christmas'+rand
                d.set_password(new_password)
                d.save()
                print(new_password)
                
                #Sending email for password reset
                try:
                    message = "Hi " + d.username +"\n \nYou are receiving this email because you requested a password reset for your Condenast Christmas Account ("+ d.email +"). \nPlease login your account with the password: "+ new_password +"\n \nNote: Please change your password after login.\n \nHave a nice day!! \n \n \nRegards \nCondeNast Christmas Team"
                    send_mail('Conde Christmas | Password Reset' , message , 'Condenast Christmas Event' , [from_email])
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                return redirect('password_reset_done')    
        
    
    return render(request, "registration/passwordreset.html", {'form': form})

@login_required(login_url='/accounts/login/')
def viewTasks(request):

    comments=Comment.objects.filter(receiver=request.user.id)
    tasks='<ol>'

    for comment in comments:
        tasks+="<center><li>"+comment.comment+"</li></center>"
    tasks+='</ol>'
    return HttpResponse(tasks)

user/templates/user/base.html
<!--users/templates/users/dashboard.html-->
<style>
    label, input {
        display: block;
    }
    span.helptext {
        display: none;
    }
</style>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Conde Christmas</title>
  </head>
  <body>
    <!-- <div class="jumbotron text-center" style="margin-bottom:0"> -->
      <h3>CondeNast</h3>
      <p><b>Chris Mom & Chris Child</b></p> 
    </div>
    
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

user/templates/user/commentbox.html
<head>{% load staticfiles%}
    <link rel="stylesheet" href="{% static 'user/design.css' %}" >
  <style>
    input[type=text] {
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
    }
    select {
      width: 50%;
      padding: 13px 21px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
    }

    

  input[type=submit] {
  background-color:#4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 10%;
  border-radius: 12px;
}
button:hover {
  opacity: 0.8;

}

    </style>
    </head>

<div class="container bootstrap snippets bootdey">
    <div class="row">
		<div class="col-md-12">
		    <div class="blog-comment">
				<h3 class="text-success">{{comments.count}} Comments</h3>
                <hr/>
                <i class="pull-right">{% csrf_token %} <form method='POST' action={% url 'comment' %}> {% csrf_token %} <label><strong>Add Your Comments</strong></label><input type='text'   name='comment' required/>
                  <label>Choose A Person</label>
                  <select name="menu" >
                    {% for each in u %}
                    {% load staticfiles%}                
                    <img src="{% static 'user/'|add:each.first_name|add:'.jpg' %}" width="150" height="150" >
                    <option value="{{each.id}}">{{each.first_name}}</option>
                   
                    {% endfor %}
                  </select>
                  
                  <input type='submit' value='Post' /></form></i>
                {% for comment in comments %}
				<ul class="comments">
				<li class="clearfix">
         
				  <img src="https://bootdey.com/img/Content/user_3.jpg" class="avatar" alt="" >
				  <div class="post-comments">
				      <p class="meta">At {{comment.created_at}} &nbsp; to {{comment}}</p>
           
<body>
				      <p>
                
				          {{comment.comment}}
              </p>
              <i class="pull-right">{% csrf_token %} <form method='POST' action={% url 'reply' comment.id %}> {% csrf_token %} <input type='text'  name='reply' required/><input type='submit' value='reply' /></form></i>
              <a onclick="getElementById('{{comment.id}}').innerHTML='{% for reply in comment.reply_set.all %}<ul><li><div ><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>At {{reply.created_at}}</strong> </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{reply.comments}}</p></div></li></ul> {% endfor %}'">{% if comment.reply_set.all.count %}{% if comment.reply_set.count == 1%}{{comment.reply_set.all.count}} Reply{% else %}{{comment.reply_set.all.count}} Replies{% endif %}{% endif %}</a>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a onclick="getElementById('{{comment.id}}').innerHTML=''">{% if comment.reply_set.all.count %}Close{% endif %}</a>
              
				  </div>
        </li>
        <div id='{{comment.id}}'></div>
        
        
			
    </ul>
        
        {% endfor %}
        
       
			</div>
		</div>
	</div>
</div>

  


</body>

user/templates/user/content.html
<center><h1>Conde Nast</h1></center>
<center><strong>ChrisMomChrisChild</strong></center>
<title>Game</title>
{% if user.is_child_assigned %}
Your Random Child is

{% for each in u %}
{% if each.id == user.child_id %}
<strong>{{each.username}}</strong>
{% endif %}
{% endfor %}

<br>
Project Team 
{% for each in UserProfile %}
{% if each.id == user.child_id %}
<strong>{{each.team_name}}</strong>
{% endif %}
{% endfor %}

{% else %}
<center><h1>Available Children</h1></center>
<ol>
  
{% for each in q %}
{% if each.is_child_assigned == False %}
<center><li>{% for name in u%}
    
    {% if name.id == each.id %}
    {{name.username}}
    {% endif %}
    {% endfor %}
</li></center>
{% endif %}
{% endfor %}

</ol>
{% csrf_token %} 
<form action ={% url 'allocateChild' user.id %} method='GET'>
    {% csrf_token %} 
    <input type="submit" value='Get Random Child'>
</form>
{% endif %}

user/templates/user/dashboard.html
{% extends "user/base.html" %}
{% block content %}
<head>
<style>
    img {
  border-radius: 50%;
}
aside {
  width: 50%;
  padding-left: 50px;
  margin-left: 1px;
  float: right;
  font-style: italic;
  
}
* {
      box-sizing: border-box;
   }
   body {
      color: #000;
      
      /* background-image: linear-gradient(135deg, #8BC6EC 0%, #9599E2 100%); */
      text-align: center;
   }
   header {
      background-color: #000;
      padding: 20px;
      text-align: center;
      color: white;
   }
   nav {
      float: left;
      width: 20%;
      height: 200px;
      
      padding: 60px 10px;
   }
   nav ul {
      list-style-type: none;
      padding: 0;
   }
   nav ul li a {
      text-decoration: none;
      
   }
   article {
      float: left;
      padding: 80px 10px;
      width: 80%;
      
      height: 200px;
      text-align: center;
   }
   section:after {
      content: "";
      display: table;
      clear: both;
   }
   footer {
      
      padding: 20px;
      text-align: center;
      
   }
</style>
    
</head>


<header>Hello, {{ user.first_name|default:'Guest' }}!
    <a href="{% url 'logout' %}">LogOut</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'password_change' %}">Change Password</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'chat' %}">Chat</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'tasks' %}">My Tasks</a>
</header>

    {% if user.is_authenticated %}
        <title>Game Dashboard</title>
        <br><br><br>

    {% if userprofile.is_child_assigned %}
    <section>
        <nav>
            <p style="float: center">Your Random Child is</p>

                {% for each in u %}
                    {% if each.id == userprofile.child_id %}
                        <strong>{{each.first_name}}</strong>
        
                        {% load staticfiles%}
   
                            <img src="{% static 'user/'|add:each.first_name|add:'.jpg' %}" width="150" height="150" style="float: left">
                
                    {% endif %}
                {% endfor %}

<br><br>
    
                {% for each in UserProfile %}
                    {% if each.id == userprofile.child_id %}
                        <strong>{{each.team_name}}</strong>
            
                    {% endif %}
                {% endfor %}

    {% else %}
    
        {% csrf_token %} 
        <form action ={% url 'allocateChild' user.id %} method='GET'>
            {% csrf_token %} 
            <input type="submit" value='Get Random Child'>
        </form>
        {% endif %}
        </nav>
<article>
    
    {% load staticfiles%}
    <img src="{% static 'user/cmcs.jpg' %}" width="250" height="250" >
    <p>It is an amusing game where Chris Child would find out who his/her Chris Mom is and do the tasks assigned by the Mom.

    The name of all the participants will be written on a different piece of paper and would be mixed up. Each one of them would be asked to pick up one. The person who took the paper is the Chris Mom for the person, whose name was written on the piece of paper taken. Till the end, no one would disclose the name they got. From the following day, it’s the duty of Chris Mom to take care of the Chris Child, either by giving tasks or by sharing gifts. Sometimes, the tasks would be funny and it will make the game quite hilarious. 
    
    This game would be played for a few days until Christmas Eve. And in the end, the suspense would be broken to the child by announcing who the Mom is. After disclosing the secret, the Chris Mom would give the Chris Child a memorable gift.
</p>
</article>

</section>
         

{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %}  
  {% endblock %}